# Site settings
title: ZYS&&TJ    				  	#你博客的标题
SEOTitle: ZYS&&TJ    	 #显示在浏览器上搜索的时候显示的标题
header-img: img/post-bg-rwd.jpg  	#显示在首页的背景图片
beginning: 2022.01.03	
description: "our room"  			 #网站介绍
url: "https://xiaohaha123qq.github.io/zystj0103.github.io/"          # 这个就是填写你的博客地址
baseurl: ""      # 这个我们不用填写

# Sidebar settings
sidebar: true                           # 是否开启侧边栏.
sidebar-about-description: "The best feeling is that when I look at you, you are already staring at me.  "
sidebar-avatar:/img/avatar-by.JPG      # 你的个人头像 这里你可以改成我在img文件夹中的两张备用照片 img/avatar-m 或 avatar-g
# SNS settings
RSS: false
weibo_username:     username
zhihu_username:     username
github_username:    username
facebook_username:  username
